### ISSUE TITLE
shu yerda "hover" va "active" berish to`g`ri bo`lmasa kerak

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/N24#11]
https://github.com/MIRZOULUGBEK9008/N24/blob/b83b979fa44f6b7ff01287887d3bafdab81c2cd0/css/styles.css#L757

**Comment by MIRZOULUGBEK9008** [comment]
Ustoz aytganlar  `:hover` va  `:active`  holatlar  ixtiyoriy deb.....
