### ISSUE TITLE
shu class bilan berilgan rasimga "hover" va "active" beribsiz maketda bu rasimga hover ishlatilmagan

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/N24#12]
**https://github.com/MIRZOULUGBEK9008/N24/blob/b83b979fa44f6b7ff01287887d3bafdab81c2cd0/index.html#L344**

**Comment by MIRZOULUGBEK9008** [comment]
`N24`  maketida  umuman  `:hover`  va  `:active`  holatlari berilmagan ustozdan so'raganimda bu narsalar ixtiyoriy deganlar demak bu `issue`  ham   #fix
