### ISSUE TITLE
`site-header`dagi qidiruv bo'limida maketdagi ikonka qo'shilmagan.

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/N24#2]
https://prnt.sc/4FeFkKUwFacR

Bu rasmdagi joyda qidiruv ikonkasi bo'lishi kerak edi. Mana bunday: https://prnt.sc/z7l_oiWCsXyQ

**Comment by MIRZOULUGBEK9008** [comment]
ustoz buni boshqa usul bilan qo`shiladi dedidlar shunga qo`shmadim
