### ISSUE TITLE
`site-footer`da ro'yxatlar orasiga `margin` berish orqali joylashtirilgan. 

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/N24#3]
https://prnt.sc/UP5v_edT5RTT

Rasmdagi ro'yxatlar orasi `203px` va `100px` `margin` lar berib joylashtirilgan. Ularni `flex` orqali joylashtirish kerak. Yani shu uchta elementni `parent` elementiga `display: flex;` va `justify-content: space-between;` berish orqali joylashtirish mumkin edi.

**Comment by MIRZOULUGBEK9008** [comment]
Aka bu xato emas maketga bir qarab qo'ying sizga yoqmagan usulda qilindi
degani xato degani emas......😐

**Comment by MIRZOULUGBEK9008** [comment]
Keyin display flex qilsangiz oxiriga taqalib qoladi shuning uchun margin
bilan ochiladi yana maketga qarang....

**Comment by MIRZOULUGBEK9008** [comment]
#fix
