### ISSUE TITLE
Google fonts ikki marta ulamaslik kerak!

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/N24#4]
https://github.com/MIRZOULUGBEK9008/N24/blob/3a3673eea16d41029da2a34de1f90c328d17a944/index.html#L12

Shu qatordagi ulangan fontlar 14-qatorda yana takroran ulangan. Hammasini bitta qilib yozish kerak.

**Comment by MIRZOULUGBEK9008** [comment]
#fix
