### ISSUE TITLE
`main-section` qismida class ochib bo'sh qoldirilgan.

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/N24#5]
https://github.com/MIRZOULUGBEK9008/N24/blob/3a3673eea16d41029da2a34de1f90c328d17a944/index.html#L88

Shu yerda klass bo'sh qoldirilgan.

**Comment by MIRZOULUGBEK9008** [comment]
#fix

**Comment by MIRZOULUGBEK9008** [comment]
To'g'rilaganman yaxshiroq qarang..
