### ISSUE TITLE
`hero` qismida ikkta `container` ochilgan, ikkalasini bitta `div`da ochish kerak edi.

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/N24#6]
https://prnt.sc/OWk4gpiGtim6

Shu rasmdagi `container` va `hero-container`larni bitta `div` ichida ochish kerak.

**Comment by MIRZOULUGBEK9008** [comment]
https://prnt.sc/YEfBT5hgWS3U


bitta `div` da ochilmaydi sababi esa  rasmda ko'rsatilgan agar bitta `div` da ochsam ushbu holat bo'ladi Demak  bu ham #fix
