### ISSUE TITLE
`CSS`da `site-header`dagi til tanlash bo'limining stillari takrorlangan.

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/N24#7]
https://github.com/MIRZOULUGBEK9008/N24/blob/3a3673eea16d41029da2a34de1f90c328d17a944/css/styles.css#L153

https://github.com/MIRZOULUGBEK9008/N24/blob/3a3673eea16d41029da2a34de1f90c328d17a944/css/styles.css#L165

Shu kodlarni bitta `class`da yozilishi kerak, chunki ikkalasiga ham bir hil stillar berilgan.

**Comment by MIRZOULUGBEK9008** [comment]
ha to'g'ri  shu joyda men  <-- DRY --> qoida siga rioya qilmapman,  bu ham #fix

**Comment by MIRZOULUGBEK9008** [comment]
To'g'rilaganman  yaxshiroq qarang....
