### ISSUE TITLE
`CSS`da `time` elementiga `class` orqali still berish kerak.

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/N24#8]
https://github.com/MIRZOULUGBEK9008/N24/blob/3a3673eea16d41029da2a34de1f90c328d17a944/css/styles.css#L360

Bu yerda `time` elementiga `class` berish orqali still berilishi kerak.

**Comment by MIRZOULUGBEK9008** [comment]
stillar 2 xil usulda beriladi(biz o'rgangan bo'yicha) 1- `class`   va 2-`tag` orqali men esa   `tag`  orqali berganman  sababi maketdagi barcha  `time`  stillari bir xil....  demak bu `issue`  ha   #fix
